blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” å•é¡Œ
    url: https://github.com/WinsonOTP/RadishBot/issues
    about: ä½ å¯ä»¥é–‹å•Ÿ Issuesï¼Œæˆ‘å€‘å¾ˆå¿«å°±æœƒç‚ºæ‚¨æä¾›æ”¯æ´!
  - name: ğŸ’¬ èŠå¤©
    url: https://discord.gg/YFGfwaNgBX
    about: æƒ³è¦èˆ‡å…¶ä»–äººè¨è«–é—œæ–¼æ©Ÿå™¨äººçš„è©±é¡Œå—? åŠ å…¥æˆ‘å€‘çš„ä¼ºæœå™¨å§!
